# Generated by Django 6.0.4 on 2026-04-17 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='scheduled', max_length=16)),
                ('assigned_diagnostician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments_as_diagnostician', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_as_client', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_created', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='vehicles.diagnosticstation')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='vehicles.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['scheduled_at'], name='appointment_sched_idx'), models.Index(fields=['status'], name='appointment_status_idx'), models.Index(fields=['scheduled_at', 'status'], name='appointment_sched_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('scheduled', 'confirmed'))), fields=('vehicle', 'scheduled_at'), name='appointment_unique_vehicle_slot_active'), models.UniqueConstraint(condition=models.Q(('status__in', ('scheduled', 'confirmed'))), fields=('station', 'scheduled_at'), name='appointment_unique_station_slot_active'), models.UniqueConstraint(condition=models.Q(('assigned_diagnostician__isnull', False), ('status__in', ('scheduled', 'confirmed'))), fields=('assigned_diagnostician', 'scheduled_at'), name='appointment_unique_diagnostician_slot_active')],
            },
        ),
    ]
