# Generated by Django 6.0.4 on 2026-04-17 17:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(default=30)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'name'], name='station_active_name_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('slot_duration_minutes__gte', 5)), name='station_slot_duration_gte_5')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(max_length=16, unique=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('make', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('production_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2027)])),
                ('vehicle_type', models.CharField(choices=[('passenger', 'Passenger'), ('truck', 'Truck'), ('bus', 'Bus'), ('motorcycle', 'Motorcycle'), ('other', 'Other')], default='passenger', max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'registration_number'], name='vehicle_owner_reg_idx')],
            },
        ),
    ]
