# Generated by Django 6.0.4 on 2026-04-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('passenger', 'Osobowy'), ('truck', 'Ciezarowy'), ('motorcycle', 'Motocykl')], default='passenger', max_length=16),
        ),
    ]
