# Generated by Django 6.0.4 on 2026-04-20

import uuid

from django.db import migrations, models


def populate_missing_qr_codes(apps, schema_editor):
    Vehicle = apps.get_model("vehicles", "Vehicle")

    for vehicle in Vehicle.objects.filter(qr_code__isnull=True).iterator():
        while True:
            candidate = uuid.uuid4().hex
            if not Vehicle.objects.filter(qr_code=candidate).exists():
                vehicle.qr_code = candidate
                vehicle.save(update_fields=["qr_code"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_alter_vehicle_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="qr_code",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.RunPython(populate_missing_qr_codes, migrations.RunPython.noop),
    ]

