# Generated by Django 6.0.4 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0002_inspectionauditevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="detected_defects",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="inspection",
            name="repair_recommendations",
            field=models.TextField(blank=True, default=""),
        ),
    ]

