from django.urls import path

from core.web.views import (
    AdminDashboardView,
    AdminUserListView,
    AdminUserUpdateView,
    AdminVehicleDeleteView,
    AdminVehicleListView,
    ClientAppointmentCancelView,
    ClientAppointmentCreateView,
    ClientAppointmentDetailView,
    ClientAppointmentsView,
    ClientDashboardView,
    ClientVehicleCreateView,
    ClientVehicleDeleteView,
    ClientVehicleDetailView,
    ClientVehicleListView,
    ClientVehicleUpdateView,
    DiagnosticianAppointmentDetailView,
    DiagnosticianInspectionResultView,
    DiagnosticianScheduleView,
    DiagnosticianVehicleByQRView,
    DiagnosticianVehicleDetailView,
    HomeView,
    LoginView,
    LogoutView,
    ProfileView,
    RegisterView,
    StationSlotsAPIView,
)

urlpatterns = [
    path("", HomeView.as_view(), name="web-home"),
    path("register/", RegisterView.as_view(), name="web-register"),
    path("login/", LoginView.as_view(), name="web-login"),
    path("logout/", LogoutView.as_view(), name="web-logout"),
    path("profile/", ProfileView.as_view(), name="web-profile"),
    path("client/dashboard/", ClientDashboardView.as_view(), name="web-client-dashboard"),
    path("client/vehicles/", ClientVehicleListView.as_view(), name="web-client-vehicles"),
    path("client/vehicles/add/", ClientVehicleCreateView.as_view(), name="web-client-vehicle-add"),
    path("client/vehicles/<int:vehicle_id>/", ClientVehicleDetailView.as_view(), name="web-client-vehicle-detail"),
    path("client/vehicles/<int:vehicle_id>/edit/", ClientVehicleUpdateView.as_view(), name="web-client-vehicle-edit"),
    path("client/vehicles/<int:vehicle_id>/delete/", ClientVehicleDeleteView.as_view(), name="web-client-vehicle-delete"),
    path("client/appointments/", ClientAppointmentsView.as_view(), name="web-client-appointments"),
    path("client/appointments/book/", ClientAppointmentCreateView.as_view(), name="web-client-appointment-book"),
    path("client/appointments/<int:appointment_id>/", ClientAppointmentDetailView.as_view(), name="web-client-appointment-detail"),
    path("client/appointments/<int:appointment_id>/cancel/", ClientAppointmentCancelView.as_view(), name="web-client-appointment-cancel"),
    path("client/stations/<int:station_id>/slots/", StationSlotsAPIView.as_view(), name="web-client-station-slots"),
    path("diagnostician/schedule/", DiagnosticianScheduleView.as_view(), name="web-diagnostician-schedule"),
    path("diagnostician/appointments/<int:appointment_id>/", DiagnosticianAppointmentDetailView.as_view(), name="web-diagnostician-appointment-detail"),
    path("diagnostician/appointments/<int:appointment_id>/result/", DiagnosticianInspectionResultView.as_view(), name="web-diagnostician-appointment-result"),
    path("diagnostician/vehicles/<int:vehicle_id>/", DiagnosticianVehicleDetailView.as_view(), name="web-diagnostician-vehicle-detail"),
    path("diagnostician/vehicles/qr/<str:qr_code>/", DiagnosticianVehicleByQRView.as_view(), name="web-diagnostician-vehicle-by-qr"),
    path("admin-panel/dashboard/", AdminDashboardView.as_view(), name="web-admin-dashboard"),
    path("admin-panel/vehicles/", AdminVehicleListView.as_view(), name="web-admin-vehicles"),
    path("admin-panel/vehicles/<int:vehicle_id>/delete/", AdminVehicleDeleteView.as_view(), name="web-admin-vehicle-delete"),
    path("admin-panel/users/", AdminUserListView.as_view(), name="web-admin-users"),
    path("admin-panel/users/<int:user_id>/edit/", AdminUserUpdateView.as_view(), name="web-admin-user-edit"),
]

